# Generated by Django 5.0 on 2026-03-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Dane 2026', 'Calculators')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly slug (auto-generated)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description for SEO')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for UI (e.g., #3B82F6)', max_length=7)),
                ('icon', models.CharField(default='📰', help_text='Emoji icon for category', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title (SEO optimized)', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated from title)', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for cards and SEO meta description', max_length=300)),
                ('content_html', models.TextField(help_text='Full HTML content of the blog post')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255)),
                ('featured_image_url', models.URLField(blank=True, help_text='URL to featured image (optional)')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'dane, 2026, progresívne zdanenie')", max_length=200)),
                ('related_calculator', models.CharField(blank=True, choices=[('salary', 'Čistá mzda'), ('mortgage', 'Hypotéka'), ('vat', 'DPH'), ('loan', 'Úver'), ('bmi', 'BMI')], help_text='Link to a specific calculator (optional)', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date/time', null=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Primary category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='calculators.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='calculators_publish_3ca95d_idx'), models.Index(fields=['status'], name='calculators_status_6c8d06_idx'), models.Index(fields=['slug'], name='calculators_slug_a4ee75_idx')],
            },
        ),
    ]
