# Generated by Django 5.0.4 on 2026-03-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Session key for anonymous users', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Optional email for notifications (even without account)', max_length=254, null=True)),
                ('calculator_type', models.CharField(choices=[('pregnancy', 'Tehotenstvo'), ('vacation', 'Dovolenka'), ('mortgage', 'Hypotéka'), ('loan', 'Úver'), ('salary', 'Čistá mzda'), ('vat', 'DPH'), ('pension', 'Dôchodok'), ('freelancer_tax', 'SZČO dane'), ('bmi', 'BMI'), ('bmr', 'BMR'), ('energy', 'Energia'), ('sick_leave', 'Nemocenská'), ('parental_benefit', 'Rodičovský príspevok'), ('fuel_cost', 'Spotreba paliva'), ('percentage', 'Percentá'), ('payment', 'Platobná kalkulačka'), ('inflation', 'Inflácia'), ('roi', 'ROI'), ('hours_worked', 'Odpracované hodiny'), ('unit_converter', 'Konvertor jednotiek'), ('car_leasing', 'Auto lízing'), ('area_volume', 'Plocha a objem'), ('split_bill', 'Rozdelenie účtu')], max_length=50)),
                ('name', models.CharField(help_text="User-defined name (e.g., 'Moje tehotenstvo - termín júl 2026')", max_length=200)),
                ('params', models.JSONField(help_text='Calculator input parameters')),
                ('result', models.JSONField(blank=True, help_text='Cached calculation result', null=True)),
                ('is_tracking', models.BooleanField(default=False, help_text='Whether user wants notifications for this calculation')),
                ('is_favorite', models.BooleanField(default=False, help_text='User-marked favorite for quick access')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Enable/disable notifications for this calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Saved Calculation',
                'verbose_name_plural': 'Saved Calculations',
                'ordering': ['-last_accessed', '-created_at'],
                'indexes': [models.Index(fields=['session_key', 'calculator_type'], name='calculators_session_dad2f4_idx'), models.Index(fields=['session_key', 'is_tracking'], name='calculators_session_44bcee_idx'), models.Index(fields=['email'], name='calculators_email_5c9d07_idx'), models.Index(fields=['-created_at'], name='calculators_created_28255b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pregnancy_week', 'Týždenná aktualizácia tehotenstva'), ('pregnancy_milestone', 'Míľnik tehotenstva'), ('trimester_change', 'Zmena trimestra'), ('prenatal_visit', 'Prenatálna kontrola'), ('due_date_approaching', 'Blíži sa termín pôrodu'), ('vacation_expiry', 'Dovolenka prepadne'), ('vacation_quarterly', 'Štvrťročná kontrola dovolenky'), ('birthday_33', 'Prírastok dovolenky (33 rokov)'), ('vacation_reminder', 'Pripomienka dovolenky'), ('payment_due', 'Splátka splatná'), ('rate_change', 'Zmena úrokovej sadzby'), ('milestone_paid', 'Míľnik splatenia'), ('amortization_alert', 'Alert amortizácie'), ('extra_payment_tip', 'Tip na nadplatenie'), ('generic_reminder', 'Všeobecná pripomienka')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Nízka'), ('medium', 'Stredná'), ('high', 'Vysoká'), ('urgent', 'Urgentná')], default='medium', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(default='09:00:00')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate on click (e.g., /calculator/pregnancy)', max_length=500, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calculators.savedcalculation')),
            ],
            options={
                'verbose_name': 'Scheduled Notification',
                'verbose_name_plural': 'Scheduled Notifications',
                'ordering': ['scheduled_date', 'scheduled_time', '-priority'],
                'indexes': [models.Index(fields=['scheduled_date', 'sent'], name='calculators_schedul_fabaaa_idx'), models.Index(fields=['calculation', 'notification_type'], name='calculators_calcula_ce937d_idx'), models.Index(fields=['sent', 'scheduled_date'], name='calculators_sent_be3dc9_idx')],
            },
        ),
    ]
