# Generated by Django 5.0 on 2026-06-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_savedcalculation_schedulednotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcalculation',
            name='calculator_type',
            field=models.CharField(choices=[('pregnancy', 'Tehotenstvo'), ('vacation', 'Dovolenka'), ('mortgage', 'Hypotéka'), ('loan', 'Úver'), ('salary', 'Čistá mzda'), ('vat', 'DPH'), ('pension', 'Dôchodok'), ('freelancer_tax', 'SZČO dane'), ('bmi', 'BMI'), ('bmr', 'BMR'), ('energy', 'Energia'), ('sick_leave', 'Pracovná neschopnosť (PN)'), ('parental_benefit', 'Rodičovský príspevok'), ('fuel_cost', 'Spotreba paliva'), ('percentage', 'Percentá'), ('payment', 'Platobná kalkulačka'), ('inflation', 'Inflácia'), ('roi', 'ROI'), ('hours_worked', 'Odpracované hodiny'), ('unit_converter', 'Konvertor jednotiek'), ('car_leasing', 'Auto lízing'), ('area_volume', 'Plocha a objem'), ('split_bill', 'Rozdelenie účtu')], max_length=50),
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(db_index=True, max_length=100)),
                ('offer_id', models.CharField(db_index=True, help_text='Identifier of the affiliate offer/placement', max_length=100)),
                ('calculator_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_url', models.URLField(max_length=600)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Affiliate Click',
                'verbose_name_plural': 'Affiliate Clicks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', '-created_at'], name='calculators_partner_a0630f_idx'), models.Index(fields=['offer_id', '-created_at'], name='calculators_offer_i_f2af27_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.CharField(choices=[('mortgage', 'Hypotéka — broker'), ('solar', 'Fotovoltika — montážna firma'), ('heat_pump', 'Tepelné čerpadlo — montážna firma'), ('renovation', 'Obnova domu — dotácie/firma'), ('insurance_car', 'PZP / havarijné poistenie'), ('accounting', 'Účtovný softvér / účtovník (SZČO)'), ('pension', 'Dôchodok / sporenie'), ('energy', 'Dodávateľ energií'), ('loan', 'Spotrebný úver'), ('other', 'Iné')], db_index=True, help_text='Lead vertical / partner program', max_length=40)),
                ('calculator_type', models.CharField(blank=True, help_text="Calculator that produced the lead (e.g. 'mortgage')", max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('region', models.CharField(blank=True, help_text='City / region — important for routing to local providers', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, help_text='Calculation inputs/results that qualify the lead (e.g. loan amount, kWp)', null=True)),
                ('consent', models.BooleanField(default=False, help_text='User consented to be contacted (GDPR)')),
                ('status', models.CharField(choices=[('new', 'Nový'), ('contacted', 'Kontaktovaný'), ('sold', 'Predaný partnerovi'), ('converted', 'Skonvertovaný'), ('rejected', 'Zamietnutý / nekvalitný')], db_index=True, default='new', max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated € value of this lead', max_digits=8, null=True)),
                ('sold_to', models.CharField(blank=True, help_text='Partner the lead was sold/routed to', max_length=150)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vertical', 'status'], name='calculators_vertica_f06d90_idx'), models.Index(fields=['-created_at'], name='calculators_created_eed79c_idx')],
            },
        ),
    ]
