# Generated by Django 5.0 on 2026-06-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0004_savedcalculation_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_type', models.CharField(blank=True, db_index=True, help_text="Calculator the report is about (e.g. 'salary', 'solar')", max_length=60)),
                ('page_url', models.CharField(blank=True, help_text='URL the user was on when reporting', max_length=600)),
                ('message', models.TextField(help_text='What the user says is wrong')),
                ('reporter_email', models.EmailField(blank=True, help_text='Optional — so we can reply / ask for details', max_length=254, null=True)),
                ('locale', models.CharField(blank=True, help_text='UI language at report time', max_length=5)),
                ('status', models.CharField(choices=[('new', 'Nový'), ('reviewing', 'Posudzuje sa'), ('fixed', 'Opravené'), ('rejected', 'Zamietnuté')], db_index=True, default='new', max_length=20)),
                ('emailed', models.BooleanField(default=False, help_text='Notification email sent to operator')),
                ('admin_notes', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Report',
                'verbose_name_plural': 'Data Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='calculators_status_242b5f_idx'), models.Index(fields=['calculator_type', '-created_at'], name='calculators_calcula_2d116e_idx')],
            },
        ),
    ]
