# Generated by Django 5.0 on 2026-06-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0005_datareport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcalculation',
            name='note',
            field=models.TextField(blank=True, default='', help_text="User's personal note about this calculation"),
        ),
        migrations.CreateModel(
            name='UserReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('custom', 'Vlastná'), ('tax', 'Daňový termín'), ('insurance', 'Poistenie'), ('finance', 'Financie'), ('home', 'Domácnosť / energie')], default='custom', max_length=20)),
                ('remind_date', models.DateField(db_index=True)),
                ('remind_time', models.TimeField(default='09:00:00')),
                ('related_calculator', models.CharField(blank=True, default='', help_text='Optional calculator slug this reminder links to', max_length=50)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reminder',
                'verbose_name_plural': 'User Reminders',
                'ordering': ['remind_date', 'remind_time'],
                'indexes': [models.Index(fields=['user', 'remind_date'], name='calculators_user_id_656bf6_idx'), models.Index(fields=['sent', 'remind_date'], name='calculators_sent_4aeb78_idx')],
            },
        ),
    ]
