# Generated by Django 5.0 on 2026-06-28 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0006_savedcalculation_note_userreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(choices=[('login', 'Prihlásenie'), ('login_failed', 'Neúspešné prihlásenie'), ('register', 'Registrácia'), ('logout', 'Odhlásenie'), ('google_login', 'Prihlásenie cez Google'), ('password_reset', 'Obnovenie hesla'), ('account_deleted', 'Zrušenie účtu')], db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auth Event',
                'verbose_name_plural': 'Auth Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='calculators_event_6c17a1_idx'), models.Index(fields=['-created_at'], name='calculators_created_441bec_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('referrer_host', models.CharField(blank=True, default='', max_length=200)),
                ('locale', models.CharField(blank=True, default='', max_length=5)),
                ('device', models.CharField(blank=True, choices=[('mobile', 'Mobil'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='', max_length=10)),
                ('visitor_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('session_key', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='calculators_created_ac725d_idx'), models.Index(fields=['path', '-created_at'], name='calculators_path_c0185e_idx')],
            },
        ),
    ]
