# Generated by Django 5.0 on 2026-06-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0007_authevent_pageview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_rate', models.DecimalField(decimal_places=2, default=0, help_text='Expected annual interest rate (%)', max_digits=5)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Goal',
                'verbose_name_plural': 'Savings Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='calculators.savingsgoal')),
            ],
            options={
                'verbose_name': 'Savings Contribution',
                'verbose_name_plural': 'Savings Contributions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user', '-created_at'], name='calculators_user_id_64c914_idx'),
        ),
    ]
