# Generated by Django 5.0 on 2026-06-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0008_savingsgoal_savingscontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreminder',
            name='frequency',
            field=models.CharField(choices=[('once', 'Jednorazovo'), ('daily', 'Denne'), ('weekly', 'Týždenne'), ('monthly', 'Mesačne'), ('yearly', 'Ročne')], default='once', max_length=10),
        ),
        migrations.AddField(
            model_name='userreminder',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Recurring reminders keep firing while active; set False to pause/stop.'),
        ),
    ]
