# Generated by Django 5.0 on 2026-06-28 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0009_userreminder_frequency_userreminder_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_id', models.CharField(db_index=True, max_length=50)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calculator Rating',
                'verbose_name_plural': 'Calculator Ratings',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['calculator_id', '-updated_at'], name='calculators_calcula_600c30_idx')],
                'unique_together': {('user', 'calculator_id')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_id', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_calculators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Calculator',
                'verbose_name_plural': 'Favorite Calculators',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['user', 'order'], name='calculators_user_id_0b469c_idx')],
                'unique_together': {('user', 'calculator_id')},
            },
        ),
    ]
