from calculators.services.salary_calculator import SalaryCalculator

calc = SalaryCalculator()

print("=" * 80)
print("TEST: DAŇOVÝ BONUS ZA DETI (CHILD TAX BONUS)")
print("=" * 80)
print()

# Test 1: Bez detí
print("TEST 1: Mzda 1500 € BEZ DETÍ")
print("-" * 80)
result1 = calc.calculate(1500, 0, 0)
print(f"Hrubá mzda:              {result1['gross_salary']:.2f} €")
print(f"Sociálne:                {result1['social_insurance']:.2f} €")
print(f"Zdravotné:               {result1['health_insurance']:.2f} €")
print(f"Daňový základ:           {result1['tax_base']:.2f} €")
print(f"NČZD:                    {result1['non_taxable_amount']:.2f} €")
print(f"Zdaniteľný základ:       {result1['taxable_base']:.2f} €")
print(f"Daň (pred bonusom):      {result1['income_tax']:.2f} €")
print(f"Bonus za deti:           {result1['child_tax_bonus']:.2f} €")
print(f"Finálna daň:             {result1['final_tax']:.2f} €")
print(f"ČISTÁ MZDA:              {result1['net_salary']:.2f} €")
print()

# Test 2: 1 dieťa do 15 rokov
print("TEST 2: Mzda 1500 € + 1 DIEŤA DO 15 ROKOV (bonus 100 €)")
print("-" * 80)
result2 = calc.calculate(1500, 1, 0)
print(f"Hrubá mzda:              {result2['gross_salary']:.2f} €")
print(f"Sociálne:                {result2['social_insurance']:.2f} €")
print(f"Zdravotné:               {result2['health_insurance']:.2f} €")
print(f"Daňový základ:           {result2['tax_base']:.2f} €")
print(f"NČZD:                    {result2['non_taxable_amount']:.2f} €")
print(f"Zdaniteľný základ:       {result2['taxable_base']:.2f} €")
print(f"Daň (pred bonusom):      {result2['income_tax']:.2f} €")
print(f"Bonus za deti:           {result2['child_tax_bonus']:.2f} € ⭐")
print(f"Finálna daň:             {result2['final_tax']:.2f} € ⭐")
print(f"ČISTÁ MZDA:              {result2['net_salary']:.2f} € ⭐")
print(f"")
print(f"✅ ROZDIEL V ČISTEJ MZDE: +{result2['net_salary'] - result1['net_salary']:.2f} € vďaka daňovému bonusu")
print()

# Test 3: 2 deti do 15 rokov
print("TEST 3: Mzda 1500 € + 2 DETI DO 15 ROKOV (bonus 200 €)")
print("-" * 80)
result3 = calc.calculate(1500, 2, 0)
print(f"Hrubá mzda:              {result3['gross_salary']:.2f} €")
print(f"Daň (pred bonusom):      {result3['income_tax']:.2f} €")
print(f"Bonus za deti:           {result3['child_tax_bonus']:.2f} € ⭐")
print(f"Finálna daň:             {result3['final_tax']:.2f} € ⭐")
print(f"ČISTÁ MZDA:              {result3['net_salary']:.2f} € ⭐")
print(f"")
print(f"✅ ROZDIEL V ČISTEJ MZDE: +{result3['net_salary'] - result1['net_salary']:.2f} € vďaka daňovému bonusu")
print()

# Test 4: Mix detí
print("TEST 4: Mzda 2000 € + 1 DIEŤA DO 15 + 1 DIEŤA 15-18 (bonus 150 €)")
print("-" * 80)
result4 = calc.calculate(2000, 1, 1)
print(f"Hrubá mzda:              {result4['gross_salary']:.2f} €")
print(f"Daň (pred bonusom):      {result4['income_tax']:.2f} €")
print(f"Bonus za deti:           {result4['child_tax_bonus']:.2f} € ⭐")
print(f"  - Dieťa do 15:         100.00 €")
print(f"  - Dieťa 15-18:         50.00 €")
print(f"Finálna daň:             {result4['final_tax']:.2f} € ⭐")
print(f"ČISTÁ MZDA:              {result4['net_salary']:.2f} € ⭐")
print()

# Test 5: Nízka mzda - bonus môže byť obmedzený daňou
print("TEST 5: Mzda 1000 € + 2 DETI - Bonus obmedzený výškou dane")
print("-" * 80)
result5 = calc.calculate(1000, 2, 0)
print(f"Hrubá mzda:              {result5['gross_salary']:.2f} €")
print(f"Zdaniteľný základ:       {result5['taxable_base']:.2f} €")
print(f"Daň (pred bonusom):      {result5['income_tax']:.2f} €")
print(f"Požadovaný bonus:        200.00 € (2 deti × 100 €)")
print(f"Uplatnený bonus:         {result5['child_tax_bonus']:.2f} € ⚠️ (limitované výškou dane)")
print(f"Finálna daň:             {result5['final_tax']:.2f} €")
print(f"ČISTÁ MZDA:              {result5['net_salary']:.2f} €")
print()

print("=" * 80)
print("ZÁVER:")
print("=" * 80)
print("✅ Daňový bonus za deti sa správne počíta a znižuje daň")
print("✅ Bonus nemôže prevýšiť výšku dane (daň nemôže byť záporná)")
print("✅ Výsledná čistá mzda sa zvyšuje vďaka daňovému bonusu")
print("=" * 80)
